name: 'Hello World'
description: 'Greet someone'
inputs:
  type:
    description: could be message, start, finish
    required: false
    default: message
  project:
    description: name of the project (repository name is used if omitted)
    default: ""
  message:
    description: message to post on Slack
    default: ""
  job_url:
    description: deprecated not used anymore
    default: ""
  SLACK_WEBHOOK_URL:
    description: Slack webhook url
    required: true


runs:
  using: "composite"
  steps:
    - name: Fetch job check run information
      id: fetch-check-run
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const { data } = await github.rest.actions.listJobsForWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          });
          const job = data.jobs.find(
            (j) => j.name.includes(context.job)
          )
          core.setOutput("job_url", job.html_url);
          core.setOutput("job_id", String(job.id));

    - name: Prepare report status
      shell: bash
      id: report-status
      run: |
        PROJECT="${{ inputs.projet }}"

        if [ -z "$PROJECT" ]; then
          PROJECT="${{ github.repository }}"
          PROJECT=${PROJECT##*\/}
        fi

        if [ "${{ inputs.type }}" == "message" ]; then
          SLACK_TEXT_MESSAGE="${{ inputs.message }}"

        elif [ "${{ inputs.type }}" == "start" ]; then
          SLACK_TEXT_MESSAGE="*Starting deployment (${{ steps.fetch-check-run.outputs.job_id }}) of $PROJECT*"

        elif [ "${{ inputs.type }}" == "finish" ]; then

          if [ "${{ job.status }}" == "success" ] ; then
            emoji="🦾"
          elif [ "${{ job.status }}" == "cancelled" ] ; then
            emoji="✋"
          else
            emoji="💥"
          fi

          JOB_ID="${{ steps.fetch-check-run.outputs.job_id }}"
          SLACK_TEXT_MESSAGE=$(cat <<EOF
        *Deployment ($JOB_ID) of $PROJECT finished ${emoji}*
        Conclusion: ${{ job.status }}
        \`\`\`
        $(git log -1)
        \`\`\`
        EOF
          )

        else
          echo "Unsupported notification type: ${{ inputs.type }}"
          exit 1
        fi

        # Replace newline with explicit \n
        SLACK_TEXT_MESSAGE=$(echo "$SLACK_TEXT_MESSAGE" | awk '{printf "%s\\n", $0}')
        echo "SLACK_TEXT_MESSAGE=${SLACK_TEXT_MESSAGE}" >> "$GITHUB_OUTPUT"


    - uses: slackapi/slack-github-action@v1.23.0
      with:
        # yamllint disable rule:line-length
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.report-status.outputs.SLACK_TEXT_MESSAGE }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Job log",
                    "emoji": true
                  },
                  "url": "${{ steps.fetch-check-run.outputs.job_url }}"
                }
              }
            ]
          }
        # yamllint enable rule:line-length
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
